version: '3.8'

services:
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - 'prodeko-org-redis:/data'

  prodeko_org:
    image: prodekoregistry.azurecr.io/prodeko-org/prodeko-org:latest
    restart: unless-stopped
    command: gunicorn prodekoorg.asgi:application -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
    volumes:
      - ./prodekoorg:/code/prodekoorg
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=prodekoorg.settings.prod

volumes:
  prodeko-org-redis:
    external: true

networks:
  default:
    external:
      name: prodeko-docker-net
