version: '3.8'

services:
  redis:
    image: redis:6

  prodeko_org:
    image: prodekoregistry.azurecr.io/prodeko-org/prodeko-org
    command: gunicorn prodekoorg.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000:8000'

networks:
  default:
    external:
      name: prodeko-docker-net
