name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup variables
        run: cp prodekoorg/settings/variables.sample.txt prodekoorg/settings/variables.txt

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build the docker-compose stack
        run: docker-compose up -d

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Run pytest
        run: docker logs prodeko_org

      - name: Run pytest
        run: docker exec prodeko_org pytest --cov prodekoorg/

      - name: Upload coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: .coverage

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Download coverage
        uses: actions/download-artifact@v2

      - name: Run coverage
        run: |
          coverage report --fail-under=70
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
