name: Run tests, upload artefacts to Codecov and Sentry

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup variables
        run: cp prodekoorg/settings/variables.sample.txt prodekoorg/settings/variables.txt

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Start docker-compose stack
        run: docker-compose up -d

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '45s'

      - name: Run pytest
        run: docker exec prodeko_org pytest --cov --cov-report=xml prodekoorg/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/prodeko-org/prodeko-org
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/prodeko-org/prodeko-org

      - name: Sentry release
        uses: getsentry/action-release@v1.1.2
        env:
          SENTRY_URL: https://sentry.prodeko.org/
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: prodeko
          SENTRY_PROJECT: prodeko-org
        with:
          environment: production
